export const countries = [
  { code: "SV", name: "El Salvador", flag: "🇸🇻", dial_code: "503" },
  { code: "GT", name: "Guatemala", flag: "🇬🇹", dial_code: "502" },
  { code: "HN", name: "Honduras", flag: "🇭🇳", dial_code: "504" },
  { code: "NI", name: "Nicaragua", flag: "🇳🇮", dial_code: "505" },
  { code: "CR", name: "Costa Rica", flag: "🇨🇷", dial_code: "506" },
  { code: "PA", name: "Panamá", flag: "🇵🇦", dial_code: "507" },
  { code: "CO", name: "Colombia", flag: "🇨🇴", dial_code: "57" },
  { code: "VE", name: "Venezuela", flag: "🇻🇪", dial_code: "58" },
  { code: "EC", name: "Ecuador", flag: "🇪🇨", dial_code: "593" },
  { code: "PE", name: "Perú", flag: "🇵🇪", dial_code: "51" },
  { code: "BO", name: "Bolivia", flag: "🇧🇴", dial_code: "591" },
  { code: "CL", name: "Chile", flag: "🇨🇱", dial_code: "56" },
  { code: "AR", name: "Argentina", flag: "🇦🇷", dial_code: "54" },
  { code: "PY", name: "Paraguay", flag: "🇵🇾", dial_code: "595" },
  { code: "UY", name: "Uruguay", flag: "🇺🇾", dial_code: "598" },
  { code: "BR", name: "Brasil", flag: "🇧🇷", dial_code: "55" },
  { code: "MX", name: "México", flag: "🇲🇽", dial_code: "52" },
  { code: "US", name: "United States", flag: "🇺🇸", dial_code: "1" },
  { code: "ES", name: "España", flag: "🇪🇸", dial_code: "34" }
];